version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/dogPlay
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: psql_dog_play
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  postgres_data:
